### ISSUE TITLE
gfServer error 

### ISSUE THREAD

**Issue by jambler24** [cauyrd/ScanIndel#10]
I have set up the tool to run on a vagrant VM and I am getting this error in the attached gfserver.temp.log file
[gfserver.temp.log](https://github.com/cauyrd/ScanIndel/files/1983900/gfserver.temp.log)

**Comment by cauyrd** [comment]
Please restart your VM or computer and run ScanIndel again, then it should
be solved. If you still have the proble. run the following command: gfServer
stop localhost 50000

**Comment by jambler24** [comment]
Running the command:
`gfServer stop localhost 50000`
solved this issue.
