### ISSUE TITLE
vcfcombine

### ISSUE THREAD

**Issue by rdcoletta** [cauyrd/ScanIndel#2]
Hello, thanks for this tool!

Just a quick question: is "vcfcombine" a required software? Because it's not listed in the README file, but I keep getting this error: `Checking for 'vcfcombine': ERROR - could not find 'vcfcombine'`

Would the file `vcf-combine.py` in `tools` directory do the same thing?

Thank you!

**Comment by cauyrd** [comment]
Hi,

vcfcombine is not required any more. I have modified my code. Please update ScanIncel.py file to fix this bug.

See my recent commit https://github.com/cauyrd/ScanIndel/commit/3bf71e49b54be18d62e4c487608a461b74af5883

Rendong

**Comment by jambler24** [comment]
When running docker image, the following error is generated:

`python: can't open file '/usr/local/bin/tools/vcf-combine.py': [Errno 2] No such file or directory
`
